export const AppAction = {
  APP_LOADING: 'APP_LOADING',
  APP_MESSAGE: 'APP_MESSAGE'
};

export const UserAction = {
  LOGOUT: 'LOGOUT',
  ACCOUNTKIT_AUTH: 'ACCOUNTKIT_AUTH',
  ACCOUNTKIT_AUTH_SUCCESS: 'ACCOUNTKIT_AUTH_SUCCESS',
  ACCOUNTKIT_AUTH_FAILURE: 'ACCOUNTKIT_AUTH_FAILURE',
  VERIFY_AUTH: 'VERIFY_AUTH',
  VERIFY_AUTH_SUCCESS: 'VERIFY_AUTH_SUCCESS',
  VERIFY_AUTH_FAILURE: 'VERIFY_AUTH_FAILURE',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
  GET_COMPANY: 'GET_COMPANY',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  SWITCH_COMPANY: 'SWITCH_COMPANY'
}

export const CustomerAction = {
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER'
}

export const ProductAction = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT'
}

export const AdminUserAction = {
  ADMIN_GET_USERS: 'ADMIN_GET_USERS',
  ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER'
}

export const AdminCompanyAction = {
  ADMIN_GET_COMPANIES: 'ADMIN_GET_COMPANIES',
  ADMIN_UPDATE_COMPANY: 'ADMIN_UPDATE_COMPANY'
}